### ISSUE TITLE
update the  Search ,Items ,Help, Cart buttons

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#13]

**Comment by ayan-joshi** [comment]
yes I will work on it

**Comment by sagnik3788** [comment]
@ayan-joshi  i will assign these issues to the other contributers please try to create some new issues ;)

**Comment by kavya020805** [comment]
![Screenshot 2023-10-18 162114](https://github.com/sagnik3788/FlavorFleet/assets/142385565/84ebbfc6-5db4-4776-aec1-53be6e7f3395)
i have updated the button, tell me if its ok and are there any changes to be made or somethings else to do.

**Comment by kavya020805** [comment]
![Screenshot 2023-10-18 162114](https://github.com/sagnik3788/FlavorFleet/assets/142385565/914aa6e4-9c08-4b59-a488-7a2a734aa6e6)
