### ISSUE TITLE
fix Forgot password page

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#14]
only update  the background image and fix links

**Comment by ayan-joshi** [comment]
I can work on it @sagnik3788

**Comment by abhinab-choudhury** [comment]
Can I work in issues

**Comment by sagnik3788** [comment]
@abhinab-choudhury already assigned please try to find some new issues

**Comment by sagnik3788** [comment]
@ayan-joshi are you still working on it

**Comment by ayan-joshi** [comment]
> @ayan-joshi are you still working on it

@sagnik3788 yes

**Comment by sagnik3788** [comment]
@ayan-joshi any update

**Comment by SadanandMiskin** [comment]
assign it to me , if the issue hasn't been solved yet

**Comment by SadanandMiskin** [comment]
@sagnik3788 what kind of image need to be added as background image?

**Comment by sagnik3788** [comment]
@SadanandMiskin  same as the login page
