### ISSUE TITLE
Improve search bar 

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#2]
**Is your feature request related to a problem? Please describe.**
I would like to improve the aesthetics of the search bar on our food website to make it visually more appealing and user-friendly.

**Describe the solution you'd like**
Please redesign the search bar to make it cleaner, more modern, and visually attractive while retaining its basic search functionality.

**Additional context**
A visually appealing search bar can enhance the overall user experience and make it more inviting for users to search for recipes and restaurants on our website.

**Comment by abhinab-choudhury** [comment]
hi, I think there is some problem in package.json. 
I can't run my app localy.

What do you use for this Project : 
- create react-react-app
- vite 
- something else
