### ISSUE TITLE
Improve Help for Customers and Help for Restaurants

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#20]
Make help section more responsive

**Comment by kavya020805** [comment]
I can do it...assign it to me

**Comment by kavya020805** [comment]
I can do it... @sagnik3788  assign it to me

**Comment by sagnik3788** [comment]
@kavya020805 after solve this issue share a sample video of the updated part

**Comment by kavya020805** [comment]
@sagnik3788 
Let me know if you want to add anything else...
https://github.com/sagnik3788/FlavorFleet/assets/142385565/974d78ff-79e4-4bdb-9580-4918e17d15e1

**Comment by kavya020805** [comment]
@sagnik3788 check and let me know

**Comment by sagnik3788** [comment]
@kavya020805  customers and restaurants are not looks same and the faq section questions ans are not responsive please follow 
customers  section for fonts and alignment

**Comment by sagnik3788** [comment]
for reference you can follow swiggy faq section

**Comment by kavya020805** [comment]
ok

**Comment by kavya020805** [comment]
https://github.com/sagnik3788/FlavorFleet/assets/142385565/e041a990-9870-486f-b717-56928eca9364

@sagnik3788 How is it now??

**Comment by sagnik3788** [comment]
looks good @kavya020805  create a pr
