### ISSUE TITLE
update FlavorFleet logo 

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#21]

**Comment by kavya020805** [comment]
@sagnik3788 
I can make good logo, assign it to me

**Comment by kavya020805** [comment]
![logo 1](https://github.com/sagnik3788/FlavorFleet/assets/142385565/c80f2f5f-d5e4-4b41-9617-1473e42febf2)
![logo 2](https://github.com/sagnik3788/FlavorFleet/assets/142385565/00b0122a-cc51-4407-a803-3a72b7585c0a)
![logo 3](https://github.com/sagnik3788/FlavorFleet/assets/142385565/6cb759a6-2760-40f8-b32f-4782488b5f3d)

Let me know which one is better...

**Comment by sagnik3788** [comment]
@kavya020805 1st
