### ISSUE TITLE
Quick links not working

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#3]
**Is your feature request related to a problem? Please describe.**
Quick links on the website are currently not functioning as intended, causing user frustration and navigation issues.

**Describe the solution you'd like**
I would like to request a fix for the quick links to ensure they work correctly. This involves identifying and resolving any technical issues that are preventing the links from functioning as expected.

**Comment by Aloksh42** [comment]
Can you please tell me ,how do I run the project locally after npm install , there are no scripts in it?

**Comment by sagnik3788** [comment]
Hi @Aloksh42, after cloning the repo, you should run the `user-server.js` and `dish-server.js` servers. Then, open it in your browser using the specific port for `user-server.js.`
If you face any issues during the setup, please let me know.

**Comment by Aloksh42** [comment]
Thnx, now it is running

**Comment by Aloksh42** [comment]
Yeah I will try to work on the issues you have created, can I raise a PR if I could solve it ?

**Comment by sagnik3788** [comment]
yes after solving you can create a pr

**Comment by Aloksh42** [comment]
Hey @sagnik3788  is it possible for you to add Hactoberfest tag on it ?
