### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#37]

**Comment by SadanandMiskin** [comment]
What does it mean by fix deployment? please provide detail

**Comment by Bhuvangoyal466** [comment]
Can I work on this ??

**Comment by sanketshinde3001** [comment]
I'll Help you to deploy your project to github pages. so that it will show updates website every time you merge any PR

**Comment by sanketshinde3001** [comment]
Can you assign me this task

**Comment by sagnik3788** [comment]
@SadanandMiskin currently when you try to  deploy on vercel   it will show errors in the code you can fix it by  adding  vercel.json  
let me know if you want to work on it

**Comment by SadanandMiskin** [comment]
> @SadanandMiskin currently when you try to  deploy on vercel   it will show errors in the code you can fix it by  adding  vercel.json  
> let me know if you want to work on it 

Yes sure will try working on it.

**Comment by SadanandMiskin** [comment]
@sagnik3788 Do you want me to include a vercel.json in repo ?

**Comment by sagnik3788** [comment]
@SadanandMiskin yes

**Comment by SadanandMiskin** [comment]
@sagnik3788 what is the source file ?

**Comment by sagnik3788** [comment]
@SadanandMiskin  its the `user-server.js` file
