### ISSUE TITLE
Home Page Not responsive.

### ISSUE THREAD

**Issue by sidharth2829** [sagnik3788/FlavorFleet#38]
I have looked into the css file of Home page. And it is not responsive.

I will add media queries to make the page responsive across different devices.

So please assign this to me.
<img width="1440" alt="Screenshot 2023-12-29 at 12 47 58 AM" src="https://github.com/sagnik3788/FlavorFleet/assets/111569459/aa056450-758a-45be-ac48-cdf2ceca679c">

**Comment by sagnik3788** [comment]
@sidharth2829 good issue you can start work on it

**Comment by sidharth2829** [comment]
Thank you

**Comment by sidharth2829** [comment]
@sagnik3788, I have made the home page responsive for almost all screen sizes, and i have made the PR.

**Comment by sagnik3788** [comment]
share the ss of the  updated part i will merge after 1st Jan

**Comment by sidharth2829** [comment]
ss of the code or website?

**Comment by sagnik3788** [comment]
3-4 ss of different section of the Website

**Comment by sidharth2829** [comment]
https://github.com/sagnik3788/FlavorFleet/assets/111569459/66c0e883-748b-4e09-9302-5236cc5fc21f

**Comment by sidharth2829** [comment]
@sagnik3788, there was a issue with the base code, that most of the sizes were in pixels, so making the page responsive was quite tough.

**Comment by sagnik3788** [comment]
Ok looks good 💯

**Comment by sidharth2829** [comment]
thank you

**Comment by Y-ash-h** [comment]
Hi @TeeWrath ! I'm interested in fixing this issue.
Please assign this issue to me.
