### ISSUE TITLE
improve Help for Customers dropdowns

### ISSUE THREAD

**Issue by sagnik3788** [sagnik3788/FlavorFleet#4]

**Comment by ayan-joshi** [comment]
Okay I want to work on this @sagnik3788

**Comment by sagnik3788** [comment]
go ahead @ayan-joshi

**Comment by ayan-joshi** [comment]
@sagnik3788 I have a doubt a start script is missing in package-json , so my local setup is not getting started can u help

**Comment by sagnik3788** [comment]
@ayan-joshi  yes there are some issues i will create another issue for it till now run the `dish-server.js` and `user-server.js` two server and use the port of `user-server.js` in your local browser

**Comment by ayan-joshi** [comment]
> @ayan-joshi yes there are some issues i will create another issue for it till now run the `dish-server.js` and `user-server.js` two server and use the port of `user-server.js` in your local browser

okay great thanks

**Comment by sagnik3788** [comment]
give @ayan-joshi 75 points
