### ISSUE TITLE
"Search Page" not responsive

### ISSUE THREAD

**Issue by sidharth2829** [sagnik3788/FlavorFleet#42]
<img width="1185" alt="Screenshot 2023-12-30 at 4 55 20 PM" src="https://github.com/sagnik3788/FlavorFleet/assets/111569459/9eacd9d5-5b3d-4443-8ffe-f3003664ae23">

Please assign me this issue under SWOC'24.

**Comment by anamithrak15** [comment]
I would like to contribute on this issue. Please assign this to me under swoc'24.
