### ISSUE TITLE
"Help Page" footer section not properly aligned.

### ISSUE THREAD

**Issue by sidharth2829** [sagnik3788/FlavorFleet#45]
<img width="1181" alt="Screenshot 2023-12-30 at 6 48 22 PM" src="https://github.com/sagnik3788/FlavorFleet/assets/111569459/419548d9-bb38-4a9f-b1f2-3ccf32389ad8">

Footer section is misaligned on mobile and tablet devices.
Please assign this issue to me under SWOC'24.

**Comment by Y-ash-h** [comment]
Hi @TeeWrath ! I'm interested in fixing this issue.
Please assign this issue to me.

**Comment by sidharth2829** [comment]
@sagnik3788 , i guess i have merged this issue's commit in the PR #39 , named "Fixed the footer alignment of help page"

76d15a51840f628fcc1e29ea65e3253767bb86a4
