### ISSUE TITLE
Enhance the typography

### ISSUE THREAD

**Issue by muskan42** [sagnik3788/FlavorFleet#46]
The typography of the site is quite basic. I would like to enhance it and add effects as well.
@sagnik3788 Please assign me the issue under SWOC'24.

**Comment by RajuC0der** [comment]
Please assign me this issue under SWOC'24
 @sagnik3788

**Comment by sagnik3788** [comment]
@muskan42 any update

**Comment by muskan42** [comment]
yes, I have committed the changes. Please review my PR.
