### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by abhinab-choudhury** [sagnik3788/FlavorFleet#9]
![1_img](https://github.com/sagnik3788/FlavorFleet/assets/132006996/193d4dd8-eb20-4863-ac90-8a5b86ddc869)

improve it

**Comment by abhinab-choudhury** [comment]
do you need some more changes in README.md

**Comment by sagnik3788** [comment]
can you share a screenshot of the readme part @abhinab-choudhury

**Comment by abhinab-choudhury** [comment]
![1_img](https://github.com/sagnik3788/FlavorFleet/assets/132006996/d8cca20a-4764-4110-82cb-01761b8937ed)
